title: Naufan Rusyda Faikar
email: mail@naruaika.me
phone: +62 821-3000-3006
description: >-
  Offering expert solutions and consultations
  for your business growth using technology.
baseurl: ""
url: "https://naruaika.me"

# Build settings
include:
  - .well-known
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag