title: Naufan Rusyda Faikar
email: hello@naruaika.me
phone: +62 821-3000-3006
social: "@naruaika"
description: >-
  Offering expert solutions and consultations
  for your business growth using technology.
baseurl: ""
url: "https://naruaika.me"

permalink: /post/:title.html

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

include:
  - .well-known

timezone: "Asia/Jakarta"